# Generated by Django 5.1.5 on 2025-01-15 01:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('belts', '0002_technique_day_technique_video_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='technique',
            name='day',
        ),
        migrations.RemoveField(
            model_name='technique',
            name='video_link',
        ),
    ]
