# Generated by Django 5.1.5 on 2025-01-15 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('belts', '0003_remove_technique_day_remove_technique_video_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='technique',
            name='video_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
